apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hugo-app
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: hugo-app
    spec:
      containers:
        - name: hugo-app
          image: smesch/hugo-app:1.0
          ports:
            - containerPort: 80