apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hugo-app-rolling-update
spec:
  minReadySeconds: 20
  replicas: 6
  template:
    metadata:
      labels:
        app: hugo-app-rolling-update
    spec:
      containers:
        - name: hugo-app
          image: smesch/hugo-app:red
          ports:
            - containerPort: 80
